config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'heros#index'

  resources :heros do
    resources :monsters, except: [:index, :show]
  end

  resources :monsters
  resources :users
  resource :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ActiveRecord::Base
  has_many :monsters

  #you could add in a helper method in battles.rb (once you create it) that matches a hero's weapon_strength against a monster's health; that would be dope!!
end

app/models/monster.rb
class Monster < ActiveRecord::Base
  belongs_to :hero

  #you could add in a helper method in battles.rb (once you create it) that matches a hero's weapon_strength against a monster's health; that would be dope!!
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :heros
  has_many :monsters  
  # you may not need the has_many monsters since heroes already possess monsters, i think this potentially complicates ERD
  # I like that you handrolled users and sessions! great practice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user   # Here we're saying "run the method set_current_user before every controller action"

  # definitely where you want this method!
  def set_current_user
    if User.exists?(session[:user_id])    # If there is a user_id currently stored in the session hash...
      @current_user = User.find(session[:user_id])  # ...find and save that user in @current_user
    else
      @current_user = nil   # ...otherwise, set @current_user to nil
    end
  end

end

# solid project and solid effort overall-- it seems like you've acquired much more comfort with rails! hopefully this is helping you to tackle angular! nice work, Ba!

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  # you can dry this section up with a before_action method
  # i.e. before_action :set_hero, except: [:index, :new, :create]
  # def set_hero
  #   Hero.find(params[:id])
  # end

  def index
    @heros = Hero.all
  end

  def new
    # nice and concise login check! love this style over the other
    redirect_to root_path unless @current_user
    @hero = Hero.new
  end

  def create
    @hero = Hero.create!(hero_params)
    redirect_to @hero
  end

  def show
    @hero = Hero.find(params[:id])
  end

  def edit
    @hero = Hero.find(params[:id])
  end

  def update
    @hero = Hero.find(params[:id])
    @hero.update(hero_params)
    redirect_to @hero
  end

  def destroy
    @hero = Hero.find(params[:id])
    @hero.destroy
    redirect_to heros_path
  end

  private
  def hero_params
    params.require(:hero).permit(:name, :img_url, :weapon_strength)
  end


end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  # see other controller for comment about DRYing up code with before_action
  def index
    @monsters = Monster.all
  end

  def new

    @monster = Monster.new
  end

  def create

    @monster = Monster.create!(monster_params)
    redirect_to @monster
  end

  def show
    @monster = Monster.find(params[:id])
  end

  def edit
    @monster = Monster.find(params[:id])
  end

  def update
    @hero = Hero.find(params[:id])
    @monster = @hero.monsters.update(monster_params)
    redirect_to hero_monster_path(@monster)
  end

  def destroy
    @monster = Monster.find(params[:id])
    @monster.destroy
    redirect_to monsters_path
  end

  private
  def monster_params
    params.require(:monster).permit(:name, :img_url, :health, :habitat, :hero_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # nice hand-rolled session controller
  def new
    @user = User.new
  end

  def create
  input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)

      if @user.password == params[:user][:password]
        flash[:notice] = "You're signed in!"
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash[:alert] = "Wrong username or password!"
        redirect_to new_session_path
      end
    else
      flash[:alert] = "That user doesn't exist!"
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    flash[:alert] = "You're signed out!"
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # nice handrolled users & sessions
  def index
    # you may want to add an is_admin row/attribute to users and maybe all users only viewable by an admin
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to users_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_url unless @current_user == @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/battles/index.html.erb
#I'd remove these from the master branch and check outa new brand to add in the many-to-many table and model

app/views/heros/edit.html.erb
<div class="content">
<h2>Edit current hero!</h2>
<ul>
<%= form_for @hero do |f| %>
  <li>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </li>
  <br>
  <li>
    <%= f.label :hero_strength %>
    <%= f.text_field :weapon_strength %>
  </li>
  <br>
  <li>
    <%= f.label :photo %>
    <%= f.text_field :img_url %>
  </li>
  <br>
    <%= f.submit "Edit!"%>
</ul>
<% end %>


<%= link_to "Delete!", @hero, method: :delete, class: "delete" if @current_user %>
</div>

app/views/heros/index.html.erb
<div class="content">
<h2>Create Your Own Hero! <%= link_to("(+)", new_hero_path) if @current_user %></h2>

<h3>Current Heroes:</h3>
<ol>
  <% @heros.each do |hero| %>
    <li>
      <%= link_to hero.name, hero %>
    </li>
    <br>
  <% end %>
</ol>
</div>

app/views/heros/new.html.erb
<div class="content">
<h2>Create a new hero!</h2>
<ul>
  <%= form_for [@hero] do |f| %>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <br>
    <li>
      <%= f.label :hero_strength %>
      <%= f.text_field :weapon_strength %>
    </li>
    <br>
    <li>
      <%= f.label :photo %>
      <%= f.text_field :img_url %>
    </li>
    <br>
      <%= f.submit "Create!"%>
  <% end %>
</ul>
</div>

app/views/heros/show.html.erb
<div class="content">
<h2><%= @hero.name %> <%= link_to "(Edit Hero)", edit_hero_path(@hero) if @current_user %></h2>
<h4>Hero Power: <%= @hero.weapon_strength %></h4>

<%= image_tag @hero.img_url, class: "hero-photo" %>

<ul>
  <p><%= @hero.name %> will be slaying : </p>
  <% @hero.monsters.each do |monster| %>
    <li><%= link_to "#{monster.name}", monster %></li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slayer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Anton|Permanent+Marker" rel="stylesheet">
  </head>
  <nav class = "slaybar">
    <img src="<%= asset_path( 'hammer.png' ) %>" alt="hammer logo" style="width:50px;height:50px;"/>
    <h1><%= link_to "Slay.R", root_url %></h1>
    <img src="<%= asset_path( 'sword.png' ) %>" alt="sword logo" style="width:50px;height:50px;"/>
  </nav>
  <nav class="slaybar">
  <% if @current_user %>
    <%= link_to "Welcome, #{@current_user.username}!", user_path(@current_user) %>
    <%= link_to "Sign Out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Sign In", new_session_path %>
  <% end %>
  </nav>
  <% flash.each do |type, message| %>
  <p class="<%= type %>"><%= message %></p>
  <% end %>
  <nav class="navbar">
    <%= link_to "Monsters", monsters_path %>
    <%= link_to "Heroes", heros_path %>
    <%= link_to "Existing Users", users_path %>
  </nav>
  <body>
    <%= yield %>
  </body>
  <footer>
    <p> Created by: Ba Phan</p>
  </footer>
</html>

app/views/monsters/edit.html.erb
<div class="content">
<h2>Edit Monsters</h2>
<ul>
  <%= form_for @monster do |f| %>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <br>
    <li>
      <%= f.label :habitat %>
      <%= f.text_field :habitat %>
    </li>
    <br>
    <li>
      <%= f.label :health %>
      <%= f.text_field :health %>
    </li>
    <br>
    <li>
      <%= f.label :photo %>
      <%= f.text_field :img_url %>
    </li>
    <br>
  <%= f.submit "Edit!"%>
</ul>
<% end %>
<%= link_to "Delete!", @monster, method: :delete, class: "delete" %>
</div>

app/views/monsters/index.html.erb
<div class="content">
<h2>Create a new monster! <%= link_to("(+)", new_monster_path) if @current_user %></h2>

<h3>Existing Monsters:</h3>
<ul>
  <% @monsters.each do |monster| %>
    <li>
      <%= link_to monster.name, monster %>
    </li>
    <br>
  <% end %>
</ul>
</div>

app/views/monsters/new.html.erb
<div class="content">
<h2>Create a new monster!</h2>
  <ul>
    <%= form_for [@monster] do |f| %>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <br>
    <li>
      <%= f.label :habitat %>
      <%= f.text_field :habitat %>
    </li>
    <br>
    <li>
      <%= f.label :health_points%>
      <%= f.text_field :health %>
    </li>
    <br>
    <li>
      <%= f.label :photo %>
      <%= f.text_field :img_url %>
    </li>
    <br>
    <li>
      Assign to: <%= f.collection_select :hero_id, Hero.order(:name),:id,:name, include_blank: false %>
    </li>
    <br>
      <%= f.submit "Create!"%>
  </ul>
<% end %>
</div>

app/views/monsters/show.html.erb
<div class="content">
<h2><%= @monster.name %> <%= link_to "(Edit Monster)", edit_monster_path(@monster) if @current_user %></h2>
<h4>Health Points: <%= @monster.health %></h4>
<h4>Habitat: <%= @monster.habitat %></h4>
<h4>Currently assigned to hero ID: <%= @monster.hero_id %> </h4>
<%= link_to "Delete this creature!", @monster, method: :delete, class: "delete" if @current_user %>

<%= image_tag @monster.img_url, class: "monster-photo" %>
</div>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
<ul>
  <%= form_for @user do |f| %>
    <li>
      <%= f.label :set_new_username %>
      <%= f.text_field :username %>
    </li>
    <br>
    <li>
      <%= f.label :set_new_password %>
      <%= f.password_field :password %>
    </li>
    <br>
    <%= f.submit "Submit" %>
  <% end %>
</ul>

<%= link_to "Delete!", @user, method: :delete, class: "delete" %>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<ul>
  <%= form_for @user do |f| %>
    <li>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </li>
    <br>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
    <br>
    <%= f.submit "Register Account" %>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2><%= @user.username %> <%= link_to("(edit)", edit_user_path(@user)) if @current_user == @user %></h2>
<%= link_to "Delete!", @hero, method: :delete, class: "delete" if @current_user == @user %>